[package]
name = "probes"
version = "0.0.1"
authors = ["Thijs Cadier <thijs@appsignal.com>",
           "Robert Beekman <robert@appsignal.com>",
           "Timon Vonk <mail@timonv.nl>"]

[dependencies]
libc = ">= 0.2.0"
time = ">= 0.1.34"
